#!/usr/bin/env bash
root=`pwd`

for repodata in $(get_repos); do
  cd $root

  repo=`get_repo $repodata`
  project=`get_project_name $repodata`  
  rname=`get_repo_name ${repo}`
  reposdir=`get_repos_dir ${project} ${rname}`

  mkdir -p $reposdir || true
  [ -d "$root/$reposdir/$rname" ] || {
    rama=`get_rama $repodata`
    echo -ne "  [ $reposdir >> $rname ]\n"
    cd $reposdir

    pwd 
    echo $repo
    git clone $repo
  }

done
