#!/bin/bash
root=`pwd`

function template() {
echo "
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: $1-pdb
spec:
  minAvailable: $2
  selector:
    matchLabels:
      app: $1"
}

cd $root
for app in $(ls); do
  echo -en "\n» $app \n  "
  cd "$app";
  notprocessed="";
  for f in $(ls); do
    cat $f | grep 'PodDisruptionBudget' > /dev/null
    if [ "$?" == "0" ]; then

      replicasinfile=`cat $f | grep -c 'replicas:'`      

      HPAminR=`cat $f | grep 'minReplicas:' | cut -d: -f2 | sed  ':begin;$!N;s/\n//;tbegin' | sed "s/ //g"`
      replicas=`cat $f | grep 'replicas:' | cut -d: -f2 | sed ':begin;$!N;s/\n//;tbegin' | sed "s/ //g"`

      if \
        [ "$HPAminR" != "$replicas" ] && \
        [ "$HPAminR" != "" ] && \
        [ "$replicasinfile" == "1" ];
      then
       
        absfile=`pwd`/$f
        sed -i "s;replicas: $replicas;replicas: $HPAminR;g" $absfile
      else
        notprocessed+="|$f|"
      fi
    fi
  done
  #if [ "$notprocessed" != "" ]; then
  # echo "¡[Files unprocessed]!:"
  # echo $notprocessed;
  #fi
  cd $root
done

echo -en "\n";