#!/bin/bash 
root=`pwd`

function template() {
echo "
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: $1-pdb
spec:
  minAvailable: $2
  selector:
    matchLabels:
      app: $1"
}

cd $root
for app in $(ls); do
  echo -en "\n» $app \n  "
  cd "$app";
  for f in $(ls); do
    cat $f | grep 'PodDisruptionBudget' > /dev/null
    if [ "$?" == "0" ]; then
      absfile=`pwd`/$f
      content=`sedf $absfile`
      echo "$content" > $absfile
    fi
  done
  cd $root
done

echo -en "\n";