#!/bin/bash

echo  "Updating branch from Master"

root=`pwd`
changes=0

branch=`git branch | grep "*" | sed 's;*;;g' | sed 's;\s;;g'`

git checkout master && \
git pull && \
git checkout $branch && \
git merge master 

echo "Done."

